//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonhill.SlimSSH.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Dragonhill.SlimSSH.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ProtocolVersionExchange_LineTooLong {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_LineTooLong", resourceCulture);
            }
        }
        
        public static string ProtocolVersionExchange_LineInvalid {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_LineInvalid", resourceCulture);
            }
        }
        
        public static string ProtocolVersionExchange_InvalidVersion {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_InvalidVersion", resourceCulture);
            }
        }
        
        public static string ProtocolVersionExchange_InvalidSoftwareVersion {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_InvalidSoftwareVersion", resourceCulture);
            }
        }
        
        public static string SshConnectionBase_NotStarted {
            get {
                return ResourceManager.GetString("SshConnectionBase_NotStarted", resourceCulture);
            }
        }
        
        public static string SshConnectionBase_ConnectCalledTwice {
            get {
                return ResourceManager.GetString("SshConnectionBase_ConnectCalledTwice", resourceCulture);
            }
        }
        
        public static string SshConnectionBase_ClosedUnexpectedly {
            get {
                return ResourceManager.GetString("SshConnectionBase_ClosedUnexpectedly", resourceCulture);
            }
        }
        
        public static string Packet_TooLarge {
            get {
                return ResourceManager.GetString("Packet_TooLarge", resourceCulture);
            }
        }
        
        public static string Packet_PayloadOutOfRange {
            get {
                return ResourceManager.GetString("Packet_PayloadOutOfRange", resourceCulture);
            }
        }
        
        public static string NameList_InvalidCharacter {
            get {
                return ResourceManager.GetString("NameList_InvalidCharacter", resourceCulture);
            }
        }
        
        public static string NameList_EmptyString {
            get {
                return ResourceManager.GetString("NameList_EmptyString", resourceCulture);
            }
        }
        
        public static string Packet_NoMessageId {
            get {
                return ResourceManager.GetString("Packet_NoMessageId", resourceCulture);
            }
        }
        
        public static string Transport_ExpectedKexInit {
            get {
                return ResourceManager.GetString("Transport_ExpectedKexInit", resourceCulture);
            }
        }
        
        public static string SshConnectionBase_ErrorTransmittingDisconnect {
            get {
                return ResourceManager.GetString("SshConnectionBase_ErrorTransmittingDisconnect", resourceCulture);
            }
        }
        
        public static string Packet_MacError {
            get {
                return ResourceManager.GetString("Packet_MacError", resourceCulture);
            }
        }
        
        public static string Transport_UnexpectedPacket {
            get {
                return ResourceManager.GetString("Transport_UnexpectedPacket", resourceCulture);
            }
        }
        
        public static string Transport_UnexpectedClosed {
            get {
                return ResourceManager.GetString("Transport_UnexpectedClosed", resourceCulture);
            }
        }
        
        public static string Transport_KexInitWhileKexActive {
            get {
                return ResourceManager.GetString("Transport_KexInitWhileKexActive", resourceCulture);
            }
        }
        
        public static string Transport_UnexpectedNewKeys {
            get {
                return ResourceManager.GetString("Transport_UnexpectedNewKeys", resourceCulture);
            }
        }
        
        public static string Transport_NoKexAlgorithmMatch {
            get {
                return ResourceManager.GetString("Transport_NoKexAlgorithmMatch", resourceCulture);
            }
        }
        
        public static string Transport_NoKexCryptoMatch {
            get {
                return ResourceManager.GetString("Transport_NoKexCryptoMatch", resourceCulture);
            }
        }
        
        public static string Transport_NoKexMacMatch {
            get {
                return ResourceManager.GetString("Transport_NoKexMacMatch", resourceCulture);
            }
        }
        
        public static string Transport_NoKexUncompressedSupported {
            get {
                return ResourceManager.GetString("Transport_NoKexUncompressedSupported", resourceCulture);
            }
        }
        
        public static string Transport_ReservedNotZero {
            get {
                return ResourceManager.GetString("Transport_ReservedNotZero", resourceCulture);
            }
        }
        
        public static string Transport_KexCouldNotCreateSharedSecret {
            get {
                return ResourceManager.GetString("Transport_KexCouldNotCreateSharedSecret", resourceCulture);
            }
        }
        
        public static string Transport_InvalidKeyFormat {
            get {
                return ResourceManager.GetString("Transport_InvalidKeyFormat", resourceCulture);
            }
        }
        
        public static string Transport_InvalidSignatureFormat {
            get {
                return ResourceManager.GetString("Transport_InvalidSignatureFormat", resourceCulture);
            }
        }
        
        public static string Transport_SignatureVerificationFailed {
            get {
                return ResourceManager.GetString("Transport_SignatureVerificationFailed", resourceCulture);
            }
        }
    }
}
