//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragonhill.SlimSSH.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dragonhill.SlimSSH.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue has been closed.
        /// </summary>
        public static string FifoQueue_Closed {
            get {
                return ResourceManager.GetString("FifoQueue_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error with an native library..
        /// </summary>
        public static string Interop_NativeLibraryError {
            get {
                return ResourceManager.GetString("Interop_NativeLibraryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name list contains an empty string.
        /// </summary>
        public static string NameList_EmptyString {
            get {
                return ResourceManager.GetString("NameList_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name list contains invalid characters.
        /// </summary>
        public static string NameList_InvalidCharacter {
            get {
                return ResourceManager.GetString("NameList_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet MAC error.
        /// </summary>
        public static string Packet_MacError {
            get {
                return ResourceManager.GetString("Packet_MacError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packet payload does not contain a message id.
        /// </summary>
        public static string Packet_NoMessageId {
            get {
                return ResourceManager.GetString("Packet_NoMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet padding error.
        /// </summary>
        public static string Packet_PaddingError {
            get {
                return ResourceManager.GetString("Packet_PaddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payload is malformed and would exceed the given size.
        /// </summary>
        public static string Packet_PayloadOutOfRange {
            get {
                return ResourceManager.GetString("Packet_PayloadOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packet size is larger than supported.
        /// </summary>
        public static string Packet_TooLarge {
            get {
                return ResourceManager.GetString("Packet_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software version in protocol version exchange was invalid.
        /// </summary>
        public static string ProtocolVersionExchange_InvalidSoftwareVersion {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_InvalidSoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version in protocol version exchange is invalid or unsupported.
        /// </summary>
        public static string ProtocolVersionExchange_InvalidVersion {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line of the protocol version exchange is invalid.
        /// </summary>
        public static string ProtocolVersionExchange_LineInvalid {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_LineInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line of the protocol version exchange is too long.
        /// </summary>
        public static string ProtocolVersionExchange_LineTooLong {
            get {
                return ResourceManager.GetString("ProtocolVersionExchange_LineTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue entry is already used in a queue.
        /// </summary>
        public static string Queue_EntryAlreadyInQueue {
            get {
                return ResourceManager.GetString("Queue_EntryAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object has been finally disposed (reference count zero).
        /// </summary>
        public static string ReferenceCountZero {
            get {
                return ResourceManager.GetString("ReferenceCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection has been closed unexpectedly.
        /// </summary>
        public static string SshConnectionBase_ClosedUnexpectedly {
            get {
                return ResourceManager.GetString("SshConnectionBase_ClosedUnexpectedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect has already been called.
        /// </summary>
        public static string SshConnectionBase_ConnectCalledTwice {
            get {
                return ResourceManager.GetString("SshConnectionBase_ConnectCalledTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not send disconnect message to server.
        /// </summary>
        public static string SshConnectionBase_ErrorTransmittingDisconnect {
            get {
                return ResourceManager.GetString("SshConnectionBase_ErrorTransmittingDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SSH connection was not started.
        /// </summary>
        public static string SshConnectionBase_NotStarted {
            get {
                return ResourceManager.GetString("SshConnectionBase_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected message SSH_MSG_KEXINIT.
        /// </summary>
        public static string Transport_ExpectedKexInit {
            get {
                return ResourceManager.GetString("Transport_ExpectedKexInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an key in an invalid format.
        /// </summary>
        public static string Transport_InvalidKeyFormat {
            get {
                return ResourceManager.GetString("Transport_InvalidKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an sigunature in an invalid format.
        /// </summary>
        public static string Transport_InvalidSignatureFormat {
            get {
                return ResourceManager.GetString("Transport_InvalidSignatureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create shared secret.
        /// </summary>
        public static string Transport_KexCouldNotCreateSharedSecret {
            get {
                return ResourceManager.GetString("Transport_KexCouldNotCreateSharedSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received a SSH_MSG_KEXINIT while a key exchange is already in progres.
        /// </summary>
        public static string Transport_KexInitWhileKexActive {
            get {
                return ResourceManager.GetString("Transport_KexInitWhileKexActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to send a priority (KEX) message while another is queued.
        /// </summary>
        public static string Transport_MultiplePriorityMessages {
            get {
                return ResourceManager.GetString("Transport_MultiplePriorityMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client and Server could not agree on a KEX algorithm.
        /// </summary>
        public static string Transport_NoKexAlgorithmMatch {
            get {
                return ResourceManager.GetString("Transport_NoKexAlgorithmMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client and Server could not agree on a crypto algorithm.
        /// </summary>
        public static string Transport_NoKexCryptoMatch {
            get {
                return ResourceManager.GetString("Transport_NoKexCryptoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client and Server could not agree on a MAC algorithm.
        /// </summary>
        public static string Transport_NoKexMacMatch {
            get {
                return ResourceManager.GetString("Transport_NoKexMacMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote site does not support uncompressed transport.
        /// </summary>
        public static string Transport_NoKexUncompressedSupported {
            get {
                return ResourceManager.GetString("Transport_NoKexUncompressedSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer send disconnect message.
        /// </summary>
        public static string Transport_PeerDisconnect {
            get {
                return ResourceManager.GetString("Transport_PeerDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer did not understand a message send.
        /// </summary>
        public static string Transport_PeerSendUnimplemented {
            get {
                return ResourceManager.GetString("Transport_PeerSendUnimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved field was not zero.
        /// </summary>
        public static string Transport_ReservedNotZero {
            get {
                return ResourceManager.GetString("Transport_ReservedNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature verification failed.
        /// </summary>
        public static string Transport_SignatureVerificationFailed {
            get {
                return ResourceManager.GetString("Transport_SignatureVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed unexpectedly.
        /// </summary>
        public static string Transport_UnexpectedClosed {
            get {
                return ResourceManager.GetString("Transport_UnexpectedClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected disconnect packet detected.
        /// </summary>
        public static string Transport_UnexpectedDisconnect {
            get {
                return ResourceManager.GetString("Transport_UnexpectedDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unexpected SSH_MSG_NEWKEYS.
        /// </summary>
        public static string Transport_UnexpectedNewKeys {
            get {
                return ResourceManager.GetString("Transport_UnexpectedNewKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unexpected packet.
        /// </summary>
        public static string Transport_UnexpectedPacket {
            get {
                return ResourceManager.GetString("Transport_UnexpectedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User forced connection abort..
        /// </summary>
        public static string UserForceAbort {
            get {
                return ResourceManager.GetString("UserForceAbort", resourceCulture);
            }
        }
    }
}
