name: build and test dotnet
on:
  - push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: start the ssh docker container
        run: ./devops/setup-integration-tests-docker.sh

      - name: setup dotnet
        uses: actions/setup-dotnet@v3.0.0
        with:
          dotnet-version: 6.x

      - name: restore dependencies
        run: dotnet restore

      - name: run tests
        run: dotnet test --no-restore

      - name: teardown the ssh docker container
        run: ./devops/teardown-integration-tests-docker.sh
